# Generated by Django 3.1.7 on 2021-02-28 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('make', models.CharField(max_length=250)),
                ('value', models.CharField(max_length=250)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
